### ISSUE TITLE
How to configure server route tables or gateway to let the remote server visit local network?

### ISSUE THREAD

**Issue by Laruto** [hwdsl2/docker-ipsec-vpn-server#141]
## Problem

I tried to use IPsec vpn tunnel to let remote server visit services on local network.

After start the docker container, my PC can connect to the IPsec server, and my PC can visit remote service. However, when I try to ping back my PC on the server, it failed. I noticed that something need to be done, such as adding a gateway record to `route tables`, but I don't know how to.

### The following is the server's `route tables`:

![image](https://user-images.githubusercontent.com/19355223/56492825-874ef100-651f-11e9-99fb-dc309d108dae.png)

### The following is the server's IPsec status:

![image](https://user-images.githubusercontent.com/19355223/56493017-3f7c9980-6520-11e9-86e8-995eef122763.png)

Thanks!

**Comment by cmsax** [comment]
Try this:

```bash
route add -net 192.168.0.0/18 gw 192.168.42.11
```

**Comment by Laruto** [comment]
> Try this:
> 
> ```shell
> route add -net 192.168.0.0/18 gw 192.168.42.11
> ```

network is unreachable

**Comment by hwdsl2** [comment]
@Laruto Hello! AFAIK there are a few issues that prevent your use case from working with this Docker image.

Firstly, it is generally more difficult to access the VPN client’s local network from the VPN server. The reverse is normally easier.

Secondly, while connected to the VPN, you may access the VPN client itself from the VPN server using its assigned internal VPN IP (e.g. 192.168.42.10). This is true when not using Docker. However, Docker enforces isolation for the VPN container, such that access to these internal VPN IPs is possible only from inside the container, not from outside (on the Docker host).

Commands that @cmsax suggested could work if you are not using Docker, but instead set up the VPN directly using scripts from my other repo.

**Comment by 937624219** [comment]
我也想知道该怎么弄

**Comment by mkramek** [comment]
If I may, @hwdsl2 - it might be useful after all this time.
A solution I've found, using Docker Compose (state as of 2026-07-28) is to use `network_mode`.

Example using the VPN combined with Prowlarr:
```yml
services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    container_name: ipsec-vpn
    restart: unless-stopped
    privileged: true
    env_file: vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on: [vpn]
    volumes:
      - /opt/media/config/prowlarr:/config
```

In this case Prowlarr, listening on `0.0.0.0` by default, joins into the VPN's network, making it listen on the gateway's addresses. If you combine it with `nginx` configured in the same manner (with `network_mode`) and e.g. some `dnsmasq` for supplying domain names, you can easily create VPN-isolated services, available under a domain of your choice.
