### ISSUE TITLE
How to use Docker DNS to resolve other containers in compose

### ISSUE THREAD

**Issue by chb0github** [hwdsl2/docker-ipsec-vpn-server#155]
I am trying to setup something pretty simple in a compose - although it's for a minecraft server, it really could apply to anything so hopefully someone can explain how I can overcome this.

I am trying to use the native docker DNS in a compose so that those who join the VPN can resolve any of the other containers but it's evading me how since the VPN creates another interface which is where all the traffic is going (and straight out to the internet). 

Below is my compose, the idea is: connect to the vpn and set your minecraft server to "minecraft" as the host, and you're done.

```yaml
version: '3.3'
services:
  minecraft:
    build:
      context: .
    restart: always
    hostname: minecraft
    volumes:
      - world:/game/world
      - $PWD/server.properties:/game/server.properties
  vpn:
    image: hwdsl2/ipsec-vpn-server
    entrypoint: /bin/sh
    command: -c "export VPN_DNS_SRV1=$$(cat /etc/resolv.conf | grep nameserver | awk '{print $$2}') && /opt/src/run.sh"
    env_file:
      - settings.env
    restart: always
    hostname: vpn
    ports:
      - 500:500/udp
      - 4500:4500/udp
    privileged: true
volumes:
  world:
```
