### ISSUE TITLE
Failure to use local DNS server

### ISSUE THREAD

**Issue by pindab0ter** [hwdsl2/docker-ipsec-vpn-server#233]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [enabled logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs) and checked [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [x] This bug is about the IPsec VPN server Docker image, and not IPsec VPN itself

**Describe the issue**
When setting `VPN_DNS_SRV1=192.168.0.201` (which is the address of my local DNS server) requests to my *.local-domains fail to be properly resolved.

**To Reproduce**

1. Set up the docker container using:
```
volumes:
  ikev2-vpn-data:

services:
  [Other services omitted]
  vpn:
    container_name: vpn
    image: hwdsl2/ipsec-vpn-server
    restart: unless-stopped
    ports: 
      - 500:500/udp
      - 4500:4500/udp
    volumes: 
      - /lib/modules:/lib/modules:ro
      - ikev2-vpn-data:/etc/ipsec.d
    environment:
      PUID: 1000
      GUID: 1000
    env_file: 
      - ./vpn.env
    privileged: true
```
`vpn.env`:
```
VPN_IPSEC_PSK=[...]
VPN_USER=[...]
VPN_PASSWORD=[...]
VPN_DNS_NAME=[...]
VPN_DNS_SRV1=192.168.0.201
```
2. Connect through IKEv2 using the `vpnclient.mobileconfig` file
3. Try to visit `*.local`-domains

**Expected behavior**
I expect the domain to be resolved by the local DNS server.

**Logs**
[Enable logs](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#enable-libreswan-logs), check [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- Docker host OS: Debian 10
- Hosting provider (if applicable): self-hosted

**Client (please complete the following information)**
- Device: iPhone XS
- OS: 14.4
- VPN mode: IKEv2

**Additional context**
* Local DNS resolves correctly when part of the same network
* IKEv2 connection successfully established. Using this connection:
  * Non-local DNS resolves successfully
  * Visiting the local DNS server directly using it's IP address works
* Pinging the local DNS server from within the running container using it's IP address shows that the local DNS server is reachable

Does the fact that the DNS server assigns to a different subnet (`192.168.42.###`) have anything to do with this? The fact that I'm able to ping the DNS server directly from within the container makes me think no.
