### ISSUE TITLE
IKEv 客户端每次创建都有默认密码，使用VPN_PROTECT_CONFIG=no 配置不生效

### ISSUE THREAD

**Issue by k186** [hwdsl2/docker-ipsec-vpn-server#437]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
env 里面配置`VPN_PROTECT_CONFIG=no` 不生效，还是会生成密码;参考 IKEv 管理 利用镜像里面的ikev2.sh 脚本 删除客户端重新配置 还是会生成密码；参考历史 issue 里面先删除已知`.vpnconfig`配置然后 使用`sudo ikev2.sh` 会提示 sudo 不存在 报错，重新删掉Ikev 客户端重新生成还是会生成密码在`.vpnconfig` 文件内；镜像已经从官方源拉的最新的；已经尝试过删除所有配置从头来；还是会生成密码；

**期待的正确结果**
VPN_PROTECT_CONFIG=no 不生成安装密码

**相关配置**
```env
# Note: All the variables to this image are optional.
# See README for more information.
# To use, uncomment and replace with your own values.

# Define IPsec PSK, VPN username and password
# - DO NOT put "" or '' around values, or add space around =
# - DO NOT use these special characters within values: \ " '
 VPN_IPSEC_PSK=xxxxxx
 VPN_USER=xxx
 VPN_PASSWORD=xxxx

# Define additional VPN users
# - DO NOT put "" or '' around values, or add space around =
# - DO NOT use these special characters within values: \ " '
# - Usernames and passwords must be separated by spaces
 VPN_ADDL_USERS=xx
 VPN_ADDL_PASSWORDS=xx

# Use a DNS name for the VPN server
# - The DNS name must be a fully qualified domain name (FQDN)
 #VPN_DNS_NAME=vpn.xxx.xyz

# Specify a name for the first IKEv2 client
# - Use one word only, no special characters except '-' and '_'
# - The default is 'vpnclient' if not specified
 VPN_CLIENT_NAME=scalper

# Use alternative DNS servers
# - By default, clients are set to use Google Public DNS
# - Example below shows Cloudflare's DNS service
 #VPN_DNS_SRV1=119.29.29.29
 #VPN_DNS_SRV2=180.76.76.76

# Protect IKEv2 client config files using a password
# - By default, no password is required when importing IKEv2 client configuration
# - Uncomment if you want to protect these files using a random password
 VPN_PROTECT_CONFIG=no
```
```yml
version: '3'

volumes:
  ikev2-vpn-data:

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    env_file:
      - /www/wwwroot/ipsecvpn/vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - /www/wwwroot/ipsecvpn/vpn:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro

```
**服务器信息（请填写以下信息）**
- Docker 主机操作系统:  Dibian 10
