### ISSUE TITLE
使用域名连接时，vpn不起作用

### ISSUE THREAD

**Issue by hu-ximing** [hwdsl2/docker-ipsec-vpn-server#454]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除)，[启用日志](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#启用-libreswan-日志) 并查看了 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 IPsec VPN 服务器 Docker 镜像，而不是 IPsec VPN 本身

**问题描述**
创建container时用`VPN_DNS_NAME`指定域名后，Windows可以成功连接vpn，但是无法访问内网ip，公网ip也没有改变，网速变得很慢。如果创建container时不指定域名，直接使用ip地址则没有这个问题。

**重现步骤**
重现该 bug 的步骤：

1. 删除所有volumes，指定域名，启动container
```sh
docker compose up -d
```

```yml
version: '3'

services:
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server
    container_name: ipsec-vpn-server
    restart: always
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    environment:
      - VPN_DNS_NAME=vpn.example.com
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true

volumes:
  ikev2-vpn-data:
```
2. 导入`vpnclient.p12`到Windows
3. 连接成功，尝试查询公网ip，ping内网地址

**期待的正确结果**
连接vpn时查询的公网ip是vpn server的public ip，能够访问内网ip

**日志**

[auth.log](https://github.com/user-attachments/files/17636565/auth.log)

**服务器信息**
- Docker 主机操作系统: Alpine
- 服务提供商（如果适用）: 

**客户端信息**
- 设备: ThinkPad E15
- 操作系统: Windows 11 24H2
- VPN 模式: IKEv2
