### ISSUE TITLE
求解：L2TP连接尝试失败，因为安全层在初始化与远程计算机的协商时遇到一个处理错误。

### ISSUE THREAD

**Issue by sky22333** [hwdsl2/docker-ipsec-vpn-server#459]
### 客户端连接报错，希望大佬们帮帮看看，感谢
**服务端通过docker部署**
```
services:
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server
    container_name: vpn
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
    privileged: true
    volumes:
      - ./data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
```

**容器运行正常，无任何报错，使用自动生成的信息进行连接，连接类型使用的是`预共享密钥的 L2TP/IPsec`**

> win系统内置客户端
> 版本号`23H2`
> 国内连国内
> `network_mode: host`网络模式也尝试过
> 在不同的电脑也测试过
---

尝试如下修改后也是一样的报错
```
services:
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server
    container_name: vpn
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
    privileged: true
    environment:
      - VPN_PUBLIC_IP=公网IP
      - VPN_IPSEC_PSK=xxxxxx
      - VPN_USER=xxxxx
      - VPN_PASSWORD=xxxxxxxxxxxxx
      - VPN_ADDL_CONF=conn ikev1-l2tp
          keyexchange=ikev1
          ike=aes128-sha1,aes256-sha1
          phase2alg=aes128-sha1,aes256-sha1
          dpddelay=10
          dpdtimeout=90
    volumes:
      - ./data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
```
> 服务端运行正常，无报错

**udp端口也是通的**

![image](https://github.com/user-attachments/assets/389cf082-930a-433c-9d0d-823b8b2f5e34)
